### ISSUE TITLE
Scrum Meeting

### ISSUE THREAD

**Issue by zachary-nguyen** [zachary-nguyen/perk-manager#57]
Please state what you will be working on this milestone and if there any blockers

**Comment by zachary-nguyen** [comment]
Working on: Working on adding memcached to the current project
Blockers: Was having issues getting memcached to run with SpringBoot

**Comment by fareed-ah** [comment]
Working on/Worked on
- Fix sorting issues
- Add another test for sorting

Blockers: None :)

**Comment by ericcosoreanu** [comment]
Working on/Worked on
- Added perk creation details
- Updated relevant models, tests, props
